stages:
  - Build container
  - Build benchmark container
  - Deploy
  - Cleanup
  - Benchmark

before_script:
  - export PIR_MAX_INPUT_SIZE=10000
  - export PIR_INLINER_MAX_SIZE=10000
  - export PIR_DEOPT_CHAOS_SEED=$RANDOM
  - echo "PIR_MAX_INPUT_SIZE=$PIR_MAX_INPUT_SIZE PIR_INLINER_MAX_SIZE=$PIR_INLINER_MAX_SIZE PIR_DEOPT_CHAOS_SEED=$PIR_DEOPT_CHAOS_SEED"
  - export REBENCH_OPTIONS="-S -df $CI_PROJECT_DIR/benchmarks.data --commit-id=$CI_COMMIT_SHA --branch=master"
  - export REBENCH_RUN="/opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks /opt/rir/build/release"
  - export REBENCH_RUN_BL="/opt/rbenchmarking/Setup/run.sh /opt/rbenchmarking/rebench.conf /opt/rbenchmarking/Benchmarks . /opt/rir/external/custom-r /opt/graal"

rir container:
  stage: Build container
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - docker build --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA -t registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
  tags:
    - build

benchmark container:
  stage: Build benchmark container
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - cd container/benchmark
    - docker build --build-arg CI_COMMIT_SHA=$CI_COMMIT_SHA -t registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA .
    - docker push registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA

deploy:
  stage: Deploy
  except:
    - schedules
  image: docker:stable
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  before_script:
    - docker info
  variables:
    GIT_STRATEGY: none
  script:
    - echo "$CI_BUILD_TOKEN" | docker login -u "$CI_BUILD_USER" --password-stdin registry.gitlab.com
    - docker pull registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/rirvm/rir_mirror:$CI_COMMIT_SHA registry.gitlab.com/rirvm/rir_mirror:master
    - docker push registry.gitlab.com/rirvm/rir_mirror:master
    - docker pull registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
    - docker tag registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA registry.gitlab.com/rirvm/rir_mirror/benchmark:master
    - docker push registry.gitlab.com/rirvm/rir_mirror/benchmark:master
  only:
    - master

cleanup_registry:
  stage: Cleanup
  image: ruby:2.5
  before_script: []
  script:
    - echo -n "$CI_BUILD_TOKEN" | ruby container/cleanup.rb

benchmark_llvm:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:PIR-LLVM $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
  retry: 2

benchmark_pir:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    - schedules
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:PIR $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month

benchmark_rir:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    - schedules
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:RIR $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month

benchmark_gnur:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark-baseline
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
    variables:
      - $DISABLE_SPEC == "0"
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN_BL "e:GNU-R $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month
benchmark_fastr:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark-baseline
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
    variables:
      - $DISABLE_SPEC == "0"
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN_BL "e:FASTR $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 6 month

# experiments:
benchmark_noEnvSpec:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
    variables:
      - $DISABLE_SPEC == "1"
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:PIR-LLVM-NOENVSPEC $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
benchmark_noTypeSpec:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
    variables:
      - $DISABLE_SPEC == "1"
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:PIR-LLVM-NOTYPESPEC $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
benchmark_noSpec:
  image: registry.gitlab.com/rirvm/rir_mirror/benchmark:$CI_COMMIT_SHA
  stage: Benchmark
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - schedules
    variables:
      - $DISABLE_SPEC == "1"
  tags:
    - benchmarks
  script:
    - $REBENCH_RUN "e:PIR-LLVM-NOSPECULATION $REBENCH_OPTIONS"
  artifacts:
    paths:
    - benchmarks.data
    expire_in: 24 month
